spring.application.name=UltrasBackend
spring.datasource.url=jdbc:postgresql://ep-quiet-butterfly-aouh7hhj-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=requirespring.datasource.username=neondb_owner
spring.datasource.password=npg_qRe4jnbEL7Vr
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect