spring.application.name=UltrasBackend
spring.datasource.url=jdbc:postgresql://ep-quiet-butterfly-aouh7hhj-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qRe4jnbEL7Vr
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


ultras.jwt.secret=Y2hhbmdlLW1lLXRoaXMtaXMtYS1kZXYtb25seS1iYXNlNjQtc2VjcmV0LWF0LWxlYXN0LTMyLWJ5dGVz
# 24 hours in milliseconds
ultras.jwt.expiration-ms=86400000