spring.application.name=UltrasBackend
spring.datasource.url=jdbc:postgresql://ep-quiet-butterfly-aouh7hhj-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qRe4jnbEL7Vr
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

ultras.jwt.secret=Y2hhbmdlLW1lLXRoaXMtaXMtYS1kZXYtb25seS1iYXNlNjQtc2VjcmV0LWF0LWxlYXN0LTMyLWJ5dGVz
# 24 hours in milliseconds
ultras.jwt.expiration-ms=86400000

#---- Cors.
ultras.cors.allowed-origins=${ULTRAS_ALLOWED_ORIGINS:http://localhost:3000}

# ----- football API
apifootball.api-key=${APIFOOTBALL_API_KEY:dd813c731cea8914d3ab118f86fcfcf2}
apifootball.base-url=${APIFOOTBALL_BASE_URL:https://v3.football.api-sports.io}
apifootball.host-header=${APIFOOTBALL_HOST_HEADER:v3.football.api-sports.io}
apifootball.liga1.league-id=${APIFOOTBALL_LIGA1_ID:274}
apifootball.liga1.season=${APIFOOTBALL_LIGA1_SEASON:2025}
apifootball.cache.fixtures-ttl-minutes=15
apifootball.cache.live-ttl-seconds=60
